zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - 2181:2181

kafka:
  image: wurstmeister/kafka
  links:
    - zookeeper
  ports:
    - 9092:9092
  environment:
    KAFKA_ZOOKEEPER_CONNECT: 172.17.0.2:2181
    KAFKA_ADVERTISED_HOST_NAME: 172.17.0.3

mongo:
  image: mongo
  ports:
    - 27017:27017
